# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata', 'jekyll-sitemap', 'jekyll-seo-tag', 'jekyll-redirect-from', 'jemoji', 'jekyll-mentions', 'jekyll-feed']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Shift Media Project
tagline:          Native Media Development Libraries for Windows
description:      "Shift Media Project aims to provide native Windows development libraries for FFmpeg and associated dependencies to support simpler creation and debugging of rich media content directly within Visual Studio"
url:              https://github.com/ShiftMediaProject
baseurl:          /

author:
  name:           'Matthew Oliver'
  url:            https://plus.google.com/u/0/103057960284300319613

paginate:         4

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/ShiftMediaProject
